version: '3.7'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3000:3000"

  order-service:
    build:
      context: ./order-service
    ports:
      - "4000:4000"

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
