version: '3.8'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3000:3000"
    env_file:
      - .env


  order-service:
    build:
      context: ./order-service
    ports:
      - "4000:4000"
    env_file:
      - .env

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "2000:2000"
    env_file:
      - .env

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  postgres:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data:
  db-data: